apiVersion: v1
kind: Service
metadata:
  name: appdb-svc
  labels:
    name: appdb
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
  selector:
    env: appdb
